DOD-3427: Update UMP event schema
hmrc/bitwarden-manager pull request #115
Opened 2024-09-23 15:12 UTC by samhpickering

UMP is moving towards a generic SNS topic that services can subscribe to
for notifications of all user events. To make this possible, a new
message property "service_name" has been added to allow for services to
filter only relevant messages.

Add service_name property to onboard_user and offboard_user event
schemas.

----------

During testing we found that "event_name"s specified by pattern could
match substrings of the event's property. Using const only allows exact
values.

Only allow exact event_name for onboard_user and offboard_user event
schemas.

2024-09-25 09:19 UTC, wunzeco commented on bitwarden_manager/offboard_user.py
> +        },
`service_name` property is not relevant to `bitwarden_manager`.

`bitwarden_manager` does not care what service emitted the event.

Please remove this property.

2024-09-25 09:20 UTC, wunzeco commented on bitwarden_manager/onboard_user.py
> +        },
same as above

2024-09-25 09:20 UTC, wunzeco requested changes
Please make the suggested changes

2024-10-22 08:38 UTC, samhpickering commented
Closed, changed direction

2024-10-22 08:38 UTC, closed without merging